# Generated by Django 3.1.14 on 2025-07-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20250615_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
